// Kokoro's phoneme vocabulary, transcribed from the reference.
//
// 114 entries mapping one IPA character (or one punctuation mark) to the token id
// the model was trained on. Generated from `server/test/voice/fixtures/vocab.json`, which
// `scripts/record-voice-oracle.py` recorded from `kokoro_onnx.config.DEFAULT_VOCAB` — not typed
// out by hand, because a mis-keyed id is a silently different phoneme rather than an error, and
// `vocab.test.ts` asserts this table still equals that fixture.
//
// Punctuation is in here (`;` 1, `:` 2, `,` 3, `.` 4, `!` 5, `?` 6) and carries prosody: the
// pauses that make a read sound like speech rather than a list. That is why `phonemes.ts` goes to
// the trouble of putting punctuation back after the npm phonemiser strips it.
//
// A character absent from this table is **dropped**, not refused — the reference does the same,
// filtering to vocabulary members before tokenising. Dropping is the right behaviour for a stray
// symbol and the wrong one for a systematic mismatch, which is what the `oː` rule in
// `phonemes.ts` exists to prevent.

/** The longest token sequence the model accepts, including nothing else. */
export const MAX_PHONEME_LENGTH = 510;

/** IPA character to token id. */
export const VOCAB: ReadonlyMap<string, number> = new Map([
  [";", 1],
  [":", 2],
  [",", 3],
  [".", 4],
  ["!", 5],
  ["?", 6],
  ["—", 9],
  ["…", 10],
  ["\"", 11],
  ["(", 12],
  [")", 13],
  ["“", 14],
  ["”", 15],
  [" ", 16],
  ["̃", 17],
  ["ʣ", 18],
  ["ʥ", 19],
  ["ʦ", 20],
  ["ʨ", 21],
  ["ᵝ", 22],
  ["ꭧ", 23],
  ["A", 24],
  ["I", 25],
  ["O", 31],
  ["Q", 33],
  ["S", 35],
  ["T", 36],
  ["W", 39],
  ["Y", 41],
  ["ᵊ", 42],
  ["a", 43],
  ["b", 44],
  ["c", 45],
  ["d", 46],
  ["e", 47],
  ["f", 48],
  ["h", 50],
  ["i", 51],
  ["j", 52],
  ["k", 53],
  ["l", 54],
  ["m", 55],
  ["n", 56],
  ["o", 57],
  ["p", 58],
  ["q", 59],
  ["r", 60],
  ["s", 61],
  ["t", 62],
  ["u", 63],
  ["v", 64],
  ["w", 65],
  ["x", 66],
  ["y", 67],
  ["z", 68],
  ["ɑ", 69],
  ["ɐ", 70],
  ["ɒ", 71],
  ["æ", 72],
  ["β", 75],
  ["ɔ", 76],
  ["ɕ", 77],
  ["ç", 78],
  ["ɖ", 80],
  ["ð", 81],
  ["ʤ", 82],
  ["ə", 83],
  ["ɚ", 85],
  ["ɛ", 86],
  ["ɜ", 87],
  ["ɟ", 90],
  ["ɡ", 92],
  ["ɥ", 99],
  ["ɨ", 101],
  ["ɪ", 102],
  ["ʝ", 103],
  ["ɯ", 110],
  ["ɰ", 111],
  ["ŋ", 112],
  ["ɳ", 113],
  ["ɲ", 114],
  ["ɴ", 115],
  ["ø", 116],
  ["ɸ", 118],
  ["θ", 119],
  ["œ", 120],
  ["ɹ", 123],
  ["ɾ", 125],
  ["ɻ", 126],
  ["ʁ", 128],
  ["ɽ", 129],
  ["ʂ", 130],
  ["ʃ", 131],
  ["ʈ", 132],
  ["ʧ", 133],
  ["ʊ", 135],
  ["ʋ", 136],
  ["ʌ", 138],
  ["ɣ", 139],
  ["ɤ", 140],
  ["χ", 142],
  ["ʎ", 143],
  ["ʒ", 147],
  ["ʔ", 148],
  ["ˈ", 156],
  ["ˌ", 157],
  ["ː", 158],
  ["ʰ", 162],
  ["ʲ", 164],
  ["↓", 169],
  ["→", 171],
  ["↗", 172],
  ["↘", 173],
  ["ᵻ", 177],
]);
